### ISSUE TITLE
[FEATURE] - Support running a job multiple At() times a day/week/month

### ISSUE THREAD

**Issue by JohnRoesler** [go-co-op/gocron#129]
### Describe the solution you'd like

```
s.Every(1).Day().At("02:00").At("04:00").Do(func() {})
```

### Describe alternatives you've considered

```
s.Every(1).Day().At("02:00").Do(func() {})
s.Every(1).Day().At("04:00").Do(func() {})
```

**Comment by berkeyvx** [comment]
What about
```go
s.Every(1).Day().At("02:00;04:00;06:00").Do(func() {})
```
split text using `;` delimeter and store inside slice. Iterate over slice and call *ParseTime()* method on each elements in slice.

**Comment by JohnRoesler** [comment]
I like that design

**Comment by berkeyvx** [comment]
Hey John,

I can work on this feature. How you guys are deciding which solution you are going to implement?

**Comment by JohnRoesler** [comment]
Let’s go with the string split. Keeps it with one At() method call. Definitely please work on this feature!

**Comment by berkeyvx** [comment]
Hey @JohnRoesler ,

I have a question about that feature. Supporting multiple times in At() is trickier than i thought. After creating jobs in scheduler, i need to set their job functions too. It is done inside `Do(...)` method. Modifying only `At` method is not enough in this case. `Do` method must find all jobs that added during the `At` method and assign the function to the jobs. Is modifying both method is ok?

I want to be sure before putting more effort and see if i am on the right track.

**Comment by JohnRoesler** [comment]
Hey @berkeyvx I am not sure I understand how you were thinking of implementing it, but I was thinking you would change the `Job.atTime` from a `time.Duration` to a slice of `time.Duration` on the Job struct. It will make the selection of the time to run the job at more complicated, but would only be allowed for Daily, Weekly and Monthly schedules. When picking the next time to run, we'd have to first get the right day, week, month and then from the atTimes pick the next one. 

This is a problem I've been thinking about in regards to Weekdays when running weekly methods that occur on multiple weekdays. It seems like something that might be benefited from using a linked list, but I've tried out a few things and haven't found a solution I like yet. 

Let me know your thoughts!

**Comment by berkeyvx** [comment]
Your solution is very different than what i thought. 

I was going to create a new job for each timeline("02:00;04:00;06:00", using this string, 3 new jobs will be added to scheduler ). With this approach, instead of calculating next run using linked list you mentioned, scheduler will decide when to run next job. This approach will create a duplicate tasks but it saves from implementing complex next run picking.

Right now, both solution have cons and pros. And it seems like yours is correct approach. 

Tbh, i am just a student. It is hard for me to come with a rightest solution. Please let me know what you think about my approach. 

And then i will begin to try implement the solution :)
