### ISSUE TITLE
[BUG] - Cron job gets ran on startup

### ISSUE THREAD

**Issue by andschneider** [go-co-op/gocron#202]
### Describe the bug

When I start a program with a `cron` job in it, that job gets run even if the time isn't "due". For example, I have a cron job to run at 7 AM (`0 7 * * *`) and every time I run the program the job runs. 

This also happens when the job is ahead, for example at 10 PM. (Let's say I'm starting the program at 7 PM.) After trying some random cron times, it seems to be happening no matter what the cron time is.

Interestingly, this doesn't happen when using the `Every` method.

### To Reproduce

```go
// main.go
package main

import (
	"log"
	"time"

	"github.com/go-co-op/gocron"
)

func task() {
	log.Println("hello")
}

func main() {
	s := gocron.NewScheduler(time.Local)
	log.Println("starting")

	s.Cron("0 7 * * *").SingletonMode().Do(task)
	// s.Every(1).Day().At("7:00").SingletonMode().Do(task) // this works though
	s.StartBlocking()
}
```

Running the above with `go run main.go` results in:

```bash
2021/07/01 18:51:53 starting
2021/07/01 18:51:53 hello
```

### Version

- I first noticed this when updating to `1.6.2` from `1.5.0`.
- I tried `1.6.0` and it seems to work.
- `1.6.1` does not work though.

### Expected behavior

When running the above code I expect the task to not be ran as the cron ins't "due", which is what happens with version `1.5.0` or `1.6.0`.

**Comment by andschneider** [comment]
Did a tiny bit of digging and I believe it was due to this change: https://github.com/go-co-op/gocron/pull/192/files#diff-031a12d8499b1cae1c81ed55ed91b2c7563c4ba3a02139b2f7115c09cf879ab5L960

Is this now the expected behavior?

**Comment by JohnRoesler** [comment]
Ah, yes the expected behavior for any job is that it starts immediately. 

You can disable this behavior with https://pkg.go.dev/github.com/go-co-op/gocron#Scheduler.WaitForSchedule at a per job level or for the whole scheduler with https://pkg.go.dev/github.com/go-co-op/gocron#Scheduler.WaitForScheduleAll

**Comment by andschneider** [comment]
Gotcha. I totally missed those.

I'm happy to help out if you think this should be added in the documentation somewhere. Personally, I was a bit confused as it's not the expected behavior of a normal cron job.

**Comment by JohnRoesler** [comment]
@andschneider 

I think that it would be more correct as you point out to have Cron not start immediately. That's an easy change.

As for the Every job not starting immediately, that is because you are using an `At()` time. If you did `Every(5).Seconds()` it would start immediately. For cron, we don't know what the actual schedule is, so it has to be a blanket start immediately or don't.

For cron, we'd then want to add a way to start immediately if that was a desired behavior. Essentially flipping how it is now.

**Comment by andschneider** [comment]
@JohnRoesler Thanks for the information! All clear now.

**Comment by leafney** [comment]
Thanks to the developers, this library is really great.

I also encountered this kind of confusion when I used `Every`. It is recommended to explain this point in `README`.

**Comment by chenjr0719** [comment]
Hi @JohnRoesler,
I got the same question and found this issue to understand the proper configuration I can have.

The current document does mention that the job will start immediately, but it does not mention how to change this behavior by using `WaitForSchedule` or `WaitForScheduleAll`.

Could you also add another section about these two configurations? It would be very helpful. 🙏

**Comment by JohnRoesler** [comment]
@chenjr0719 @leafney updated the documentation to make it more clear 👍
