### ISSUE TITLE
[BUG] weekdays only work for weekly basis schedules

### ISSUE THREAD

**Issue by Streppel** [go-co-op/gocron#29]
### Describe the bug

```gocron.Every(2).Thursday().At("08:00").Do(taskHandler)``` does not work because we do not consider the interval on our weekday API.

### Expected behavior

```gocron.Every(2).Thursday().At("08:00").Do(taskHandler)```  should execute every 2 thursdays as soon as the scheduler begins to run 

### Additional context

Do we run at the first given thursday, then skip two? Or begin skipping two? Ideas of how to approach this are welcome

[originally posted here](https://github.com/jasonlvhit/gocron/issues/154)

**Comment by davleb** [comment]
I just had a look at the python schedule package. It is not yet implemented.
There is a discussion about that matter at stackoverflow:
https://stackoverflow.com/questions/56824553/python-run-job-every-first-monday-of-month
python package suggests a syntax like `schedule.every(3).mondays.do(test)`, so **mondays** should be used instead of **monday** but I consider `schedule.every(3).monday.do(test)` is really more consistent.

So the actual syntax is OK, it just should work.
`gocron.Every(2).Thursday().At("08:00").Do(taskHandler)`

In regard to your question it seems more natural to me that we run at the first given thursdays, then skip two.
But it is not easy feasable as the job struct has no field about whether the next execution date is the first one or not.

I think our problem is in the function
`func (s *Scheduler) scheduleNextRun(j *Job) error `

weekday jobs have a j.unit of 'week' type
when type is week, as contrary to other types (day, minute...) j.periodDuration or j.interval are completely ignored
formula is 
`j.nextRun = j.nextRun.Add(time.Duration(dayDiff) * 24 * time.Hour)`

maybe it lacks adding a period when j.interval  > 1, wich should be the case for` Every(2).Thursday()...`

`j.nextRun = j.nextRun.Add(time.Duration(dayDiff) * 24 * time.Hour  +  time.Duration(j.interval -1) * 24 * time.Hour )`

It could do the trick. What do you think ?

**Comment by Streppel** [comment]
@davleb thank you for your input. You are absolutely right as for regards the periodDuration and interval being ignored. I will progress on this over this weekend or the next one as I work on our scheduler v2 and address these issues!

**Comment by JohnRoesler** [comment]
@Streppel have you had a chance to work on this one? It seems like a valuable fix

**Comment by Streppel** [comment]
> @Streppel have you had a chance to work on this one? It seems like a valuable fix

I have to admit that it was a long weekend since my last message lol I didn't unfortunately John. Indeed, I agree with you. I'll take a look at it again and send feedback here. If you want to take a look at it too feel free just let me know beforehand

**Comment by JohnRoesler** [comment]
I was doing some testing with this and it seemed to be behaving correctly. @Streppel have you looked at this recently?

**Comment by Streppel** [comment]
@JohnRoesler as a matter of fact just tested it out and it worked fine! Guess we fixed it along the way... Closing the issue!
