### ISSUE TITLE
[BUG] - s1.StartAsync() from example doesn't work in latest release

### ISSUE THREAD

**Issue by camccar** [go-co-op/gocron#34]
### Describe the bug

Tried using the example in the readme on a project with go modules. It automatically assigns the latest release tag of `v0.1.1` in `v0.1.1` the method `StartAsync` does not exist.

### To Reproduce

1. go to a project that uses go modules
1. add the example from the readme
1. Try to compile project. You will get the error `s1.StartAsync undefined (type *gocron.Scheduler has no field or method StartAsync)`

### Version

`v0.1.1`

### Expected behavior

The example on the readme should compile with go modules.

### Additional context

N/A

**Comment by auzty** [comment]
@camccar  
it's happened to me a few days ago when starting using this module.
the root cause are the version on go module v0.1.1 not implement **StartAsync** yet.
you can use the latest branch when using go module
**go get "github.com/go-co-op/gocron@master"**
you will get the master branch. 

my **go.mod** files
```
module github.com/testku

go 1.14

require github.com/go-co-op/gocron v0.1.2-0.20200427211536-19d750d2040f // indirect
```

hope it helps, i already using the master branch using the **StartAsync**, so far my cron running for a few days with no error

**Comment by JohnRoesler** [comment]
Good call out. We have not yet released the code with that function.

**Comment by Streppel** [comment]
fixed :) https://github.com/go-co-op/gocron/releases/tag/v0.2

**Comment by camccar** [comment]
Thank you!
