### ISSUE TITLE
[QUESTION] - Best way to update events jobs

### ISSUE THREAD

**Issue by ferllings** [go-co-op/gocron#37]
Hello,

Each morning I need to adjust the time for my jobs.

What is the best way to update jobs:

1) Simply clear and re-add the job, even if the scheduler is already started?
```
 s1 := gocron.NewScheduler(time.UTC)
 s1.Every(1).Day().At("10:30").Do(task)
 s1.StartAsync()
...
s1.Clear()
 s1.Every(1).Day().At("11:00").Do(task)
```
2) or recreate the scheduler (is there a clean way to stop and remove scheduler?)
```
 s1 := gocron.NewScheduler(time.UTC)
 s1.Every(1).Day().At("10:30").Do(task)
 s1.StartAsync()
...
s1.Clear()
 s1 = gocron.NewScheduler(time.UTC)
 s1.Every(1).Day().At("11:00").Do(task)
 s1.StartAsync()
```
3) Another way?

Thanks

**Comment by Streppel** [comment]
Thanks for opening the issue, I didn't know about the need for this use case. There's no need to create another scheduler, your first example should work just fine. Also keep in mind that once your scheduler has already started there's no need to start it again.

I'll be in fact reviewing our Tags system next week because I think it'd work nicely with your use case. Whenever there's anyting new done about this it will be posted in our README file. Also, feel free to send new ideas! (what I have in mind right now is something like `.GetJobsWithTag(myTag).UpdateScheduleTime("11:00")` but I need to stress this further"

**Comment by ferllings** [comment]
Thanks for answering.
This module works great!
