### ISSUE TITLE
[FEATURE] - Expose the go context or accept a custom go context

### ISSUE THREAD

**Issue by Tochemey** [go-co-op/gocron#586]
### Is your feature request related to a problem? Please describe

At the moment I see that the scheduler starts a go context to execute jobs as shown here https://github.com/go-co-op/gocron/blob/main/scheduler.go#L112. This can be an issue during instrumentation and context propagation. This may lead to disconnected spans in traces

### Describe the solution you'd like

I am suggesting that an option is made available to pass in custom go context that will be used throughout the executions of Jobs. That way we may not observe disconnected spans during instrumentation

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by JohnRoesler** [comment]
Hi @Tochemey 

Completely agree that this is something that should be supported for cases such as yours to allow trace propagation through context. 

Currently only getting the context that is used for the job is there https://pkg.go.dev/github.com/go-co-op/gocron#Job.Context

A better feature would be to allow passing in a context rather than only letting you reference the one that was created (this is primarily for listening to the ctx.done() chan)

**Comment by JohnRoesler** [comment]
@Tochemey I was thinking on this more, and I'm not sure what would be gained by providing a context to gocron unless Gocron itself was instrumented with tracing. You are already free to pass a context to the job function and then instrument the job function with tracing if you so choose. The job's context is just used for cancellation within the context of the gocron scheduler.
