### ISSUE TITLE
[FEATURE REQUEST] - every 2 (or greater) weeks first run closer to 2 weeks rather than 1

### ISSUE THREAD

**Issue by yrcs** [go-co-op/gocron#587]
If set .Every(2).Weeks().Monday().At("10:00") or .Every(2).Weeks().Monday().Tuesday().At("10:00"), then the NextRun() method returns the next week's execution time, not the **expected next 2 weeks' execution time**.

**Comment by JohnRoesler** [comment]
The current design is that it selects the next available date/time to run and then starts the interval from there.

So, today is `Tuesday 10-10-2023 8:00`, and here are some code examples and when then first run will be:

```
s.Every(2).Weeks().Monday().Tuesday().At("10:00").Do(func() {}) => 2023-10-10 10:00:00 (2 hours away)
s.Every(2).Weeks().Monday().At("10:00").Do(func() {}) => 2023-10-16 10:00:00 (6 days away)
```

I'm going to update this issue to a feature request. It sounds like you'd like to be able to have the behavior such that the first run should be close to the interval rather than the next available weekday

**Comment by JohnRoesler** [comment]
You could achieve this behavior currently using StartAt. Here is an example:

```golang
package main

import (
	"log"
	"time"

	"github.com/go-co-op/gocron"
)

func main() {
	s := gocron.NewScheduler(time.Local)
	startAt := time.Now().Add(time.Hour * 168)
	j, err := s.Every(2).Weeks().Monday().StartAt(startAt).At("10:00").Do(func() {})
	if err != nil {
		log.Fatal(err)
	}
	s.StartAsync()
	log.Printf("nextRun: %s\n", j.NextRun())
	s.Stop()
}
```
Output:
```
nextRun: 2023-10-23 10:00:00 // this is 13 days from now
```

**Comment by yrcs** [comment]
Thanks!

**Comment by yrcs** [comment]
Thanks! My ultimate goal is to use gocron to make a scheduler module similar to Windows Task Scheduler. However, there are too many problems encountered during implementation.

![image](https://github.com/go-co-op/gocron/assets/24586688/01d0ba88-cba8-45e7-8f32-640734549a07)
