### ISSUE TITLE
[BUG] - `job.LastRun()` is not updated after calling  `job.RunNow()`

### ISSUE THREAD

**Issue by JakobDev** [go-co-op/gocron#685]
### Describe the bug

The return value of  `job.LastRun()` is not updated after calling  `job.RunNow()`

### To Reproduce

Just call `job.RunNow.` After that call `job.LastRun()`

### Version

v2.2.4

### Expected behavior

The time returned by  `job.LastRun()` should be updated.

### Additional context

The time returned by  `job.LastRun()` is not updated

**Comment by JohnRoesler** [comment]
This could be solved by having two representations of the run times. 

1. An internal representation that scheduling is based on
2. An external representation that actually shows when the last run occurred

The current implementation is just 1. above and so you're not seeing the last run updated because as the RunNow function states, it won't impact existing schedules which are determined based on the last run / next run constructs.
