### ISSUE TITLE
[FEATURE] Recovery and Restart for Singleton Jobs

### ISSUE THREAD

**Issue by hasanparasteh** [go-co-op/gocron#702]
I've been using the gocron library in my projects and have found it incredibly useful for task scheduling. However, I've encountered a scenario that I believe could be addressed to enhance its robustness and reliability.

Currently, when a Singleton job fails or panics, it remains in an inconsistent state, requiring manual intervention to restart it. My feature request is to implement automatic recovery and restart functionality for Singleton jobs within the gocron library.

Here's why I believe this feature would be beneficial:

1. Enhanced Reliability: Automatic recovery and restart of Singleton jobs would ensure that critical tasks are not left in a failed state, thereby enhancing the overall reliability of applications using the gocron library.

2. Improved Fault Tolerance: By automatically restarting Singleton jobs upon failure or panic, the library can contribute to improved fault tolerance, reducing the likelihood of service disruptions due to unforeseen errors.

3. Simplified Maintenance: With built-in recovery and restart functionality, developers would spend less time monitoring and manually restarting failed Singleton jobs, leading to simplified maintenance and reduced operational overhead.

4. Consistent Execution: Ensuring that Singleton jobs are always running as intended contributes to the consistent execution of scheduled tasks, which is crucial for applications with time-sensitive operations.

Implementing this feature would not only benefit me in managing critical tasks more effectively but also benefit other users of the gocron library who rely on its scheduling capabilities for their applications.

I'm excited about the potential improvements this feature could bring to the gocron library and would be happy to provide further input or assistance as needed. Thank you for considering my suggestion, and I look forward to seeing the continued evolution of this excellent tool.

**Comment by hasanparasteh** [comment]
I've been utilizing the gocron library extensively, particularly for managing WebSocket connections in real-time applications. In live socket connections, especially those designated as one-time singleton jobs, occasional failures or disruptions are not uncommon. These failures often necessitate a manual intervention to reconnect the WebSocket, leading to potential downtime and service interruptions.

Considering the critical role WebSocket connections play in real-time applications and the broader implications for various use cases, including critical areas such as financial transactions and monitoring systems, I believe this feature would not only benefit me but also numerous other developers relying on the gocron library for their projects.

**Comment by JohnRoesler** [comment]
Hey @hasanparasteh 

First off, thanks for the issue, thoughts and kind words. I'm glad you've found the project useful!

The two types of failure cases I see would be:
1. job function returns an error
2. job function panics 

1. In the event the job fails and returns an error. The [AfterJobRunsWithError](https://pkg.go.dev/github.com/go-co-op/gocron/v2#AfterJobRunsWithError) event listener could be used to handle this case. You can even re-run the job from within the handler with the Job's [RunNow](https://pkg.go.dev/github.com/go-co-op/gocron/v2#example-Job-RunNow) method. I would suggest that even before doing this case, you could build error handling into the job for cases such as the websocket disconnected, etc.
2. I am pretty opposed to having a "panic handler". Rather than building this functionality in, job functions should simply not panic...handle those cases within the job and if you must, use go's built in `recover` function to handle a panic and then do something about it.

Now, regarding `1.`, an argument could be made for building some features around job retries when an error is returned. Essentially, it would give users a way to tell the scheduler, this job failed, try again. I go back and forth on whether this is something gocron should support or something each job should support itself. 

It would be helpful to further understand the issues you are facing to know whether they are easily abstract able or really specific to your use case. 

Happy to continue discussing your proposal.

**Comment by hasanparasteh** [comment]
if job function returns an error we could easily handle it with `AfterJobRunsWithError`. I think my problem is out of scope for this project and with simple abstraction layers it should be recoverable.

thank you for your consideration.
